---
sort: sum                      # max|min|avg|sum|count|uri|method|max-body|min-body|avg-body|sum-body|p1|p50|p99|stddev
reverse: true                   # boolean
query_string: true              # boolean
output: count,5xx,4xx,3xx,method,uri,min,max,sum,avg,p99                    # string(comma separated)

# 必ず`^`と`&`を使った完全一致の記述を行うこと
matching_groups:            # array
  - ^/initialize$
  - ^/api/auth$
  - ^/api/signout$
  - ^/api/livestream/[0-9]+$
  - ^/api/livestream/[0-9]+/livecomment$
  - ^/api/livestream/[0-9]+/reaction$
  - ^/api/livestream/[0-9]+/report$
  - ^/api/livestream/[0-9]+/ngwords$
  - ^/api/livestream/[0-9]+/livecomment/[0-9]+/report$
  - ^/api/livestream/[0-9]+/moderate$
  - ^/api/livestream/[0-9]+/enter$
  - ^/api/livestream/[0-9]+/exit$
  - ^/api/livestream/[0-9]+/statistics$
  - ^/api/user/[\-0-9a-f]+$
  - ^/api/user/[\-0-9a-f]+/statistics$
  - ^/api/user/[\-0-9a-f]+/icon$
  - ^/api/user/[\-0-9a-f]+/theme$
  - ^/api/livestream/search?tag=[\-\%0-9a-f]+$
  - ^/api/livestream/search?limit=[0-9]+$
  - ^/api/auth$
  - ^/api/trend$
  - ^/assets$
  - ^/\?jwt
  - ^/isu/
  - ^/assets/
  - ^/register$
    #  - ^/[^a].+$


# file:                       # string
# query_string_ignore_values: # boolean
# decode_uri:                 # boolean
# format:                     # string
# limit:                      # 5000
# noheaders:                  # boolean
# show_footers:               # boolean
# filters:                    # string
# pos_file:                   # string
# nosave_pos:                 # boolean
# percentiles:                # array
# ltsv:
#   apptime_label: # apptime
#   status_label:  # status code
#   size_label:    # size
#   method_label:  # method
#   uri_label:     # uri
#   time_label:    # time
# json:
#   uri_key:           # string
#   method_key:        # string
#   time_key:          # string
#   response_time_key: # string
#   body_bytes_key:    # string
#   status_key:        # string
# regexp:
#   pattern:              # string
#   uri_subexp:           # string
#   method_subexp:        # string
#   time_subexp:          # string
#   response_time_subexp: # string
#   body_bytes_subexp:    # string
#   status_subexp:        # string
# pcap:
#   server_ips:  # array
#   server_port: # number
